// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace QUANLYSINHVIEN.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    [Migration("20221130061518_IntialCreate_Table_Qlmh")]
    partial class IntialCreateTableQlmh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("QUANLYSINHVIEN.Models.Diem", b =>
                {
                    b.Property<string>("MaSV")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiemMH")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenMH")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSV")
                        .HasColumnType("TEXT");

                    b.HasKey("MaSV");

                    b.ToTable("Diem");
                });

            modelBuilder.Entity("QUANLYSINHVIEN.Models.Khoa", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tenkhoa")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("QUANLYSINHVIEN.Models.Lop", b =>
                {
                    b.Property<string>("IdLop")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenLop")
                        .HasColumnType("TEXT");

                    b.HasKey("IdLop");

                    b.ToTable("Lop");
                });

            modelBuilder.Entity("QUANLYSINHVIEN.Models.Qlmh", b =>
                {
                    b.Property<string>("Mamonhoc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tenmonhoc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Mamonhoc");

                    b.ToTable("Qlmh");
                });

            modelBuilder.Entity("QUANLYSINHVIEN.Models.SinhVien", b =>
                {
                    b.Property<string>("IdSV")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdLop")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenLop")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSV")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tenkhoa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Điachi")
                        .HasColumnType("TEXT");

                    b.HasKey("IdSV");

                    b.HasIndex("Id");

                    b.HasIndex("IdLop");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("QUANLYSINHVIEN.Models.SinhVien", b =>
                {
                    b.HasOne("QUANLYSINHVIEN.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("Id");

                    b.HasOne("QUANLYSINHVIEN.Models.Lop", "Lop")
                        .WithMany()
                        .HasForeignKey("IdLop");

                    b.Navigation("Khoa");

                    b.Navigation("Lop");
                });
#pragma warning restore 612, 618
        }
    }
}
